version: '2'
services:
  blog-html-pc:
    container_name: "blog-html-pc"
    image: carldu/blog-html-pc:latest
    links:
      - blog-server
    ports:
      - "8003:80"
    volumes:
      - /docker_data/blog/pc/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - blog-network

  blog-html-admin:
    container_name: "blog-html-admin"
    image: carldu/blog-html-admin:latest
    links:
      - blog-server
    ports:
      - "8006:80"
    volumes:
      - /docker_data/blog/admin/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - blog-network
      
  blog-html-mobile:
    container_name: "blog-html-mobile"
    image: carldu/blog-html-mobile:latest
    links:
      - blog-server
    ports:
      - "8004:80"
    volumes:
      - /docker_data/blog/mobile/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - blog-network

  blog-db:
    image: postgres:12
    container_name: "blog-db"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: blog
    volumes:
      - /docker_data/blog/pg_data:/var/lib/postgresql/data
    networks:
      - blog-network

  blog-server:
    container_name: "blog-server"
    image: carldu/blog-server:latest
    links:
      - blog-db
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /docker_data/blog/server/appsettings.json:/app/appsettings.json
      - /docker_data/blog/server/logs:/app/log
      - /docker_data/blog/server/storage:/app/storage
    networks:
      - blog-network
      
networks:
  blog-network:
    driver: bridge