printWidth: 150 # Specify the length of line that the printer will wrap on.
singleQuote: true # Use single quotes instead of double quotes.
arrowParens: 'avoid' # 箭头函数只有一个参数不加括号
semi: true # 句尾添加分号
bracketSpacing: true # 对象和数组参数之间加空格
trailingComma: 'none'
