name: Build and Push Admin

on:
  push:
    tags:
      - "v*"
      
  # Allows you to run this workflow manually from the Actions tab
  # 可以手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tag:
        description: 'Docker image tag'
        required: false
        default: 'latest'
        
jobs:
  build-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M')"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure env for admin
        working-directory: ./admin
        run: |
          cat > .env.prod << eof
          NODE_ENV=production
          VUE_APP_INDEX_URL=${{ secrets.VUE_APP_INDEX_URL }}
          VUE_APP_AXIOS_BASE_URL=${{ secrets.VUE_APP_AXIOS_BASE_URL }}
          VUE_APP_MOBILE_URL=${{ secrets.VUE_APP_MOBILE_URL }}
          VUE_APP_TITLE=${{ secrets.VUE_APP_TITLE }}
          VUE_APP_DISQUS_SHORTNAME=${{ secrets.VUE_APP_DISQUS_SHORTNAME }}
          eof

      - name: Extract tag name
        id: tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "::set-output name=tag::${{ github.event.inputs.tag }}"
          else
            echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
          fi
          
      - name: Build and push admin
        uses: docker/build-push-action@v2
        with:
          context: ./admin
          file: ./admin/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            carldu/blog-html-admin:${{ steps.tag.outputs.tag }}
            carldu/blog-html-admin:latest
